### ISSUE TITLE
swoole/restart重启时pid文件不存在导致报错

### ISSUE THREAD

**Issue by faynwol** [liufee/yii2-swoole#20]
版本：`0.1.3`
报错信息：
```
PHP Warning 'yii\base\ErrorException' with message 'file_get_contents(/data/web/yii-application/console/config/../../frontend/runtime/server.pid): failed to open stream: No such file or directory'

in /data/web/yii-application/vendor/feehi/yii2-swoole/src/console/SwooleController.php:227

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'file_get_conten...', '/data/web/yii-a...', 227, Array)
#1 /data/web/yii-application/vendor/feehi/yii2-swoole/src/console/SwooleController.php(227): file_get_contents('/data/web/yii-a...')
#2 /data/web/yii-application/vendor/feehi/yii2-swoole/src/console/SwooleController.php(191): feehi\console\SwooleController->getPid()
#3 [internal function]: feehi\console\SwooleController->actionRestart()
#4 /data/web/yii-application/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /data/web/yii-application/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#6 /data/web/yii-application/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('restart', Array)
#7 /data/web/yii-application/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('restart', Array)
#8 /data/web/yii-application/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('swoole/restart', Array)
#9 /data/web/yii-application/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('swoole/restart', Array)
#10 /data/web/yii-application/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#11 /data/web/yii-application/yii(23): yii\base\Application->run()
#12 {main}
```

swoole版本：
```
Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.3
Built => Apr 28 2019 17:12:47
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
```

[文档](https://wiki.swoole.com/wiki/page/p-pid_file.html)描述如果Server正常退出会删除pid文件，但是似乎存在延迟，导致重启方法无法正常读取pid文件导致报错退出。

在发送SIGTERM信号后usleep(100000)可以解决，但是不确定是不是正确的方法。

**Comment by purevirtual** [comment]
`
  $this->sendSignal(SIGTERM);
        $time = 0;
        while (posix_getpgid($this->getPid()) && $time <= 10) {
            usleep(100000);
            $time++;
        }
`
你说的正确 代码中已做相应的改进
