### ISSUE TITLE
最新版yii2，安装你这个插件后访问报错yii\base\InvalidCallException: Setting read-only property: feehi\web\Session::name

### ISSUE THREAD

**Issue by neilqin** [liufee/yii2-swoole#6]
yii\base\InvalidCallException: Setting read-only property: feehi\web\Session::name in /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/base/Component.php:206
Stack trace:
#0 /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/BaseYii.php(546): yii\base\Component->__set('name', 'advanced-fronte...')
#1 /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(feehi\web\Session), Array)
#2 [internal function]: yii\base\BaseObject->__construct(Array)
#3 /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#4 /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('feehi\\web\\Sessi...', Array, Array)
#5 /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('feehi\\web\\Sessi...', Array, Array)
#6 /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/di/ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#7 /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/base/Module.php(742): yii\di\ServiceLocator->get('session', true)
#8 /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/web/Application.php(178): yii\base\Module->get('session')
#9 /home/neil/yii2/yii2-app-advanced/vendor/feehi/yii2-swoole/src/web/Response.php(242): yii\web\Application->getSession()
#10 /home/neil/yii2/yii2-app-advanced/vendor/feehi/yii2-swoole/src/web/Response.php(237): feehi\web\Response->sendCookies()
#11 /home/neil/yii2/yii2-app-advanced/vendor/feehi/yii2-swoole/src/web/Response.php(204): feehi\web\Response->sendHeaders()
#12 /home/neil/yii2/yii2-app-advanced/vendor/yiisoft/yii2/web/ErrorHandler.php(135): feehi\web\Response->send()
#13 /home/neil/yii2/yii2-app-advanced/vendor/feehi/yii2-swoole/src/web/ErrorHandler.php(39): yii\web\ErrorHandler->renderException(Object(yii\base\InvalidCallException))
#14 /home/neil/yii2/yii2-app-advanced/vendor/feehi/yii2-swoole/src/console/SwooleController.php(168): feehi\web\ErrorHandler->handleException(Object(yii\base\InvalidCallException))
#15 [internal function]: feehi\console\SwooleController->feehi\console\{closure}(Object(Swoole\Http\Request), Object(Swoole\Http\Response))
#16 /home/neil/yii2/yii2-app-advanced/vendor/feehi/yii2-swoole/src/swoole/SwooleServer.php(54): call_user_func_array(Object(Closure), Array)

**Comment by zacksleo** [comment]
见 https://github.com/liufee/yii2-swoole/pull/10
